apiVersion: v1
kind: Service
metadata:
  name: wecom-adapter
  labels:
    app.kubernetes.io/name: wecom-adapter
spec:
  selector:
    app.kubernetes.io/name: wecom-adapter
  ports:
    - name: http
      port: 8080
      targetPort: http
